import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Player from '#models/player'
import { PlayerRoleEnum } from '../../app/enums/player_role_enum.js'
import { GameColorsEnum } from '../../app/enums/game_colors_enum.js'

export default class extends BaseSeeder {
  async run() {
    // Create test players for each game (4 players per game, 2 red + 2 blue)
    await Player.createMany([
      // Game G000001 players
      {
        playerId: 'P0001',
        player_name: 'Eric Philippe',
        player_role: PlayerRoleEnum.ATTACK,
        player_goals: 3,
        player_own_goals: 0,
        player_assists: 1,
        player_saves: 2,
        possession_time: '4:32',
        mood: '🙂',
        player_comment: 'Great match!',
        team_color: GameColorsEnum.RED,
        is_substitute: 'no',
        userId: 1,
        gameId: 'G000001',
      },
      {
        playerId: 'P0002',
        player_name: 'Alex Martin',
        player_role: PlayerRoleEnum.DEFENSE,
        player_goals: 2,
        player_own_goals: 0,
        player_assists: 2,
        player_saves: 5,
        possession_time: '3:15',
        mood: '😊',
        player_comment: 'Solid defense',
        team_color: GameColorsEnum.RED,
        is_substitute: 'no',
        userId: 2,
        gameId: 'G000001',
      },
      {
        playerId: 'P0003',
        player_name: 'Marie Dubois',
        player_role: PlayerRoleEnum.ATTACK,
        player_goals: 2,
        player_own_goals: 1,
        player_assists: 0,
        player_saves: 1,
        possession_time: '2:48',
        mood: '😐',
        player_comment: 'Could be better',
        team_color: GameColorsEnum.BLUE,
        is_substitute: 'no',
        userId: 3,
        gameId: 'G000001',
      },
      {
        playerId: 'P0004',
        player_name: 'Julien Moreau',
        player_role: PlayerRoleEnum.DEFENSE,
        player_goals: 1,
        player_own_goals: 0,
        player_assists: 1,
        player_saves: 3,
        possession_time: '2:25',
        mood: '😞',
        player_comment: 'Tough loss',
        team_color: GameColorsEnum.BLUE,
        is_substitute: 'no',
        userId: 4,
        gameId: 'G000001',
      },

      // Game G000002 players
      {
        playerId: 'P0005',
        player_name: 'Sophie Bernard',
        player_role: PlayerRoleEnum.ATTACK,
        player_goals: 1,
        player_own_goals: 0,
        player_assists: 0,
        player_saves: 1,
        possession_time: '3:22',
        mood: '😔',
        player_comment: 'Need more practice',
        team_color: GameColorsEnum.RED,
        is_substitute: 'no',
        userId: 5,
        gameId: 'G000002',
      },
      {
        playerId: 'P0006',
        player_name: 'Thomas Petit',
        player_role: PlayerRoleEnum.DEFENSE,
        player_goals: 1,
        player_own_goals: 0,
        player_assists: 0,
        player_saves: 4,
        possession_time: '2:55',
        mood: '😐',
        player_comment: 'Close match',
        team_color: GameColorsEnum.RED,
        is_substitute: 'no',
        userId: 6,
        gameId: 'G000002',
      },
      {
        playerId: 'P0007',
        player_name: 'Camille Roux',
        player_role: PlayerRoleEnum.ATTACK,
        player_goals: 3,
        player_own_goals: 0,
        player_assists: 2,
        player_saves: 0,
        possession_time: '4:12',
        mood: '🎉',
        player_comment: 'Excellent game!',
        team_color: GameColorsEnum.BLUE,
        is_substitute: 'no',
        userId: 7,
        gameId: 'G000002',
      },
      {
        playerId: 'P0008',
        player_name: 'Nicolas Vincent',
        player_role: PlayerRoleEnum.DEFENSE,
        player_goals: 2,
        player_own_goals: 0,
        player_assists: 1,
        player_saves: 6,
        possession_time: '3:38',
        mood: '😄',
        player_comment: 'Great teamwork',
        team_color: GameColorsEnum.BLUE,
        is_substitute: 'no',
        userId: 8,
        gameId: 'G000002',
      },

      // Game G000003 players
      {
        playerId: 'P0009',
        player_name: 'Laura Simon',
        player_role: PlayerRoleEnum.ATTACK,
        player_goals: 3,
        player_own_goals: 0,
        player_assists: 1,
        player_saves: 2,
        possession_time: '5:23',
        mood: '🔥',
        player_comment: 'On fire today!',
        team_color: GameColorsEnum.RED,
        is_substitute: 'no',
        userId: 9,
        gameId: 'G000003',
      },
      {
        playerId: 'P0010',
        player_name: 'Antoine Garcia',
        player_role: PlayerRoleEnum.DEFENSE,
        player_goals: 2,
        player_own_goals: 0,
        player_assists: 2,
        player_saves: 7,
        possession_time: '4:44',
        mood: '💪',
        player_comment: 'Strong defense',
        team_color: GameColorsEnum.RED,
        is_substitute: 'no',
        userId: 10,
        gameId: 'G000003',
      },
      {
        playerId: 'P0011',
        player_name: 'Chloé David',
        player_role: PlayerRoleEnum.ATTACK,
        player_goals: 2,
        player_own_goals: 0,
        player_assists: 1,
        player_saves: 1,
        possession_time: '4:15',
        mood: '😤',
        player_comment: 'So close!',
        team_color: GameColorsEnum.BLUE,
        is_substitute: 'no',
        userId: 11,
        gameId: 'G000003',
      },
      {
        playerId: 'P0012',
        player_name: 'Maxime Richard',
        player_role: PlayerRoleEnum.DEFENSE,
        player_goals: 2,
        player_own_goals: 1,
        player_assists: 0,
        player_saves: 5,
        possession_time: '3:52',
        mood: '😞',
        player_comment: 'That own goal hurt',
        team_color: GameColorsEnum.BLUE,
        is_substitute: 'no',
        userId: 12,
        gameId: 'G000003',
      },

      // Game G000004 players
      {
        playerId: 'P0013',
        player_name: 'Emma Lefebvre',
        player_role: PlayerRoleEnum.ATTACK,
        player_goals: 0,
        player_own_goals: 0,
        player_assists: 1,
        player_saves: 0,
        possession_time: '2:33',
        mood: '😰',
        player_comment: 'Rough day',
        team_color: GameColorsEnum.RED,
        is_substitute: 'no',
        userId: 13,
        gameId: 'G000004',
      },
      {
        playerId: 'P0014',
        player_name: 'Lucas Michel',
        player_role: PlayerRoleEnum.DEFENSE,
        player_goals: 1,
        player_own_goals: 0,
        player_assists: 0,
        player_saves: 3,
        possession_time: '2:19',
        mood: '😕',
        player_comment: 'Dominated',
        team_color: GameColorsEnum.RED,
        is_substitute: 'no',
        userId: 14,
        gameId: 'G000004',
      },
      {
        playerId: 'P0015',
        player_name: 'Léa Martinez',
        player_role: PlayerRoleEnum.ATTACK,
        player_goals: 3,
        player_own_goals: 0,
        player_assists: 1,
        player_saves: 0,
        possession_time: '3:47',
        mood: '🚀',
        player_comment: 'Unstoppable!',
        team_color: GameColorsEnum.BLUE,
        is_substitute: 'no',
        userId: 15,
        gameId: 'G000004',
      },
      {
        playerId: 'P0016',
        player_name: 'Eric Philippe',
        player_role: PlayerRoleEnum.DEFENSE,
        player_goals: 2,
        player_own_goals: 0,
        player_assists: 2,
        player_saves: 4,
        possession_time: '3:26',
        mood: '😎',
        player_comment: 'Easy win',
        team_color: GameColorsEnum.BLUE,
        is_substitute: 'no',
        userId: 1,
        gameId: 'G000004',
      },
    ])
  }
}
